# configuration:
theme:
  name: mkdocs
  color_mode: auto
  nav_style: dark
  user_color_mode_toggle: true
  navigation_depth: 3
  locale: en

# site info
site_name: Ashley Nilson
site_url: https://ash-nil.github.io/
site_author: Ashley Nilson
site_description: >-
  A few samples of work completed by Ashley Nilson, a data analyst with a strong background in project management and an MS in Applied Data Science for Business with a Graduate Certificate in Business Intelligence & Analytics from Portland State University. 

# navigation
nav:
- Python: 
  - "Traffic Analysis": Traffic_Analysis/Traffic_Analysis.md
  - "Fraudulent Account Detection": Fraudulent_Acct_Detection/Fraudulent_Acct_Detection.md
  - "AB Game Testing": Game_AB_Testing/Game_AB_Testing.md
- R: 
  - "EV Charging Optimization": EV_Charging_Optimization/EV_Charging_Optimization.md
  - "Housing Price Prediction": Housing_Price_Prediction/Housing_Price_Prediction.md
- SQL: 
  - "Temporal Database Updates PR": Database_Updates_PR.md
  - "Temporal Database Review": Database_Updates.sql
- HBR Reports:
  - "Asante Teaching Hospital Billing (PDF)": docs/HBR_Reports/Asante.pdf
  - "Danushi Plant Manufacturing (PDF)": docs/HBR_Reports/Danshui.pdf
  - "London Water Pricing (PDF)": docs/HBR_Reports/LondonWater.pdf
  - "Police Billing Structure (PDF)": docs/HBR_Reports/PolicePricing.pdf
  - "Tidal Cloud Accounting (PDF)": docs/HBR_Reports/TidalCloud.pdf
  - "Toliza Museum of Art Admission (PDF)": docs/HBR_Reports/Toliza.pdf
