# configuration:
theme:
  name: mkdocs
  color_mode: auto
  nav_style: dark
  user_color_mode_toggle: true
  navigation_depth: 3
  locale: en

# site info
site_name: Ashley Nilson
site_url: https://ash-nil.github.io/
site_author: Ashley Nilson
site_description: >-
  A few samples of work completed by Ashley Nilson, a data analyst with a strong background in project management and an MS in Applied Data Science for Business with a Graduate Certificate in Business Intelligence & Analytics from Portland State University. 

# navigation
nav:
- Current Project: 
  - "Marketing Campaign Results (Python)": Marketing_Campaign_Results/analysis_pt1.md
- Past Projects: 
  - "Traffic Analysis (Python)": Traffic_Analysis/Traffic_Analysis.md
  - "Fraudulent Account Detection (Python)": Fraudulent_Acct_Detection/Fraudulent_Acct_Detection.md
  - "AB Game Testing (Python)": Game_AB_Testing/Game_AB_Testing.md
  - "EV Charging Optimization (R)": EV_Charging_Optimization/EV_Charging_Optimization.md
  - "Housing Price Prediction (R)": Housing_Price_Prediction/Housing_Price_Prediction.md
  - "Database Updates-PR (SQL)": Database_Updates/Database_Updates_PR.md
  - "Database Updates-Validation (SQL)": Database_Updates/Database_Updates.md
- Accounting Reports:
  - "Asante Teaching Hospital Billing": HBR_Reports/Asante.md
  - "Danshui Plant Manufacturing": HBR_Reports/Danshui.md
  - "London Water Pricing": HBR_Reports/LondonWater.md
  - "Police Billing Structure": HBR_Reports/PolicePricing.md
  - "Tidal Cloud Accounting": HBR_Reports/TidalCloud.md
  - "Toliza Museum of Art Admission": HBR_Reports/Toliza.md
